server:
  port: 8082

spring:
  application:
   name: Api-Gateway-App

  cloud:
    gateway:
      routes:
        - id: authentication-api
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

      eureka:
        instance:
          hostname=localhost:

  cloud:
    gateway:
      httpclient:
        pool:
          type: DISABLED